#!/usr/bin/env bash
# Honest status matrix: what is ENFORCED in code vs PARTIAL vs TODO for the ccloop extension.
row(){ printf '  %-40s %s\n' "$1" "$2"; }
echo "ccloop — install matrix (spec-kit extension)"
row "PROTECTED_PAT + cross-family"        "ENFORCED  (lib/common.sh)"
row "tasks.md immutability (G9)"          "ENFORCED  (freeze/gate + PROTECTED_PAT; completion in progress.md)"
row "one injected memory (G1)"            "ENFORCED  (build-context.sh denies specs/*/ccloop/**)"
row "progress ladder monotonicity"        "ENFORCED  (progress-lint.sh, fail-closed)"
row "assert-closed before human gate"     "ENFORCED  (progress-status.sh --assert-closed)"
row "human sign-off closure (G3)"         "ENFORCED  (done-gate.sh; blocks on open blocking debt)"
row "contract derive (idempotent)"        "ENFORCED  (contract-derive.sh)"
row "loop arming / data plane"            "ENFORCED  (state.sh arm → RUN_ID/ACTIVE under specs/<f>/ccloop)"
row "workflow structure (do-while)"       "ENFORCED  (workflow.yml; fail-closed shell steps)"
row "lessons.md cap (G4)"                 "ENFORCED  (lessons-lint.sh)"
row "promotion whitelist (G5)"            "ENFORCED  (promote-check.sh; ccloop-scoped promoted.jsonl)"
row "stop rules"                          "ENFORCED  (guards.sh: MAX_ITER + TIME + no-progress + oscillation)"
row "adversarial-test sandbox"            "PARTIAL   (sandbox-run.sh: --network none, else env -i + timeout)"
row "agent-CLI adapters"                  "PARTIAL   (adapters.sh normalizer live; invocation die-guarded)"
row "metrics feature-scoped ledger"       "PARTIAL   (metrics.sh reads .cc-local-loop legacy path — follow-up)"
row "node-ai dispatch / judge call"       "TODO      (die-guarded until Option-B topology, §15.5)"
row "three-valued judge (uncertain→debt)" "TODO      (needs live judge — node-ai follow-up)"
row "detach+poll for 300s steps"          "TODO      (dispatch/judge wiring — node-ai follow-up)"
row "scripts/powershell mirrors"          "TODO      (bash-first)"
echo "Legend: ENFORCED=in code · PARTIAL=some · TODO=not yet. Live dispatch stays guarded — nothing fakes green."
